docRoot                   $VH_ROOT/html
vhDomain                  $VH_NAME
vhAliases                 www.$VH_NAME
adminEmails               admin@$VH_NAME
enableGzip                1

errorlog $VH_ROOT/logs/error.log {
  useServer               0
  logLevel                WARN
}

accesslog $VH_ROOT/logs/access.log {
  useServer               0
}

scripthandler  {
  add                     lsapi:lsphp82 php
}

rewrite  {
  enable                  1
  autoLoadHtaccess        1
}
